print("hello you! ik ben jan")
print("wie ben jij")
inputtxt = input ()
print("hallo", inputtxt)
print("ik ben nieuw op het mediacollege")
print("het is een nieuwe ervaring voor me")
print("maar ik ben helemaal tevreden waar ik nu ben")
print("heb jij huisdieren?")
print("A ik heb geen huisdieren")
print("B ik heb 2 katten en een hond")
print("C ik heb een vis")
inputtxt = input ()
if inputtxt == "A":
    print("nee dombo")
    print("jij bent zelf een dombo")
    print("):")
if inputtxt == "B":
    print("juist")
    print("WAT!!")
    print("ja")
    print("een dier is genoeg")
    print("niet voor mijn familie")
if inputtxt == "C":
    print("vissen zijn saai")
    print("maakt toch niet uit")
    print("jij doe jij")
    print("dieren zij gewoon leuk")
print("over familie gesproken")
print("hoeveel familie heb jij thuis")
print("A alleen een vader en moeder")
print("B twee broertjes en vader en moeder")
print("C ik met mijn moeder en twee broertjes")
inputtxt == input ()
if inputtxt == "A":
    print ("nee dat is fout")
    print("jammer dan was het zo stil geweest")
    print("je raakt er gewend aan")
if inputtxt == "B":
    print("nee geen vader")
    print("echt waar?")
    print("ja")
if inputtxt == "C":
    print("dat is hem")
    print("hoe kan je moeder dat nou alleen")
    print("ze is best wel goed voor een moeder")
print("en wat vind je lekker eten")
print("goede vraag")
print("A hamburger patat fastfood")
print("B rijst zalm soup enzo")
print("C spaghetti lasange")
inputtxt == input ()
if inputtxt == "A":
    print("een lekkere snackba~")
    print("nee")
    print("oh dat was een test")
    print("ja ja")
if inputtxt == "B":
    print("er zijn lekkere dingen dan dat")
    print("ja dat is waar")
if inputtxt == "C":
    print("daar ben ik het mee eens")
    print("hmmm heerlijk")
    print("hmmmm")
    print('hmmm')
print